### PR TITLE
fix: make website-generator more stable

### LINKED ISSUE #78: Pin textchecker-element.es.js version
https://github.com/textlint/editor/blob/68a6beee0576aa8d5d0a9fca5561d1d4869ed813/packages/textchecker-element/tools/website-generator.ts#L10

This script version should be pinned.
Or copy dist on generating website.

It will be broken in the future.

### PR DESCRIPTION
**Pull request by azu**
- Use bundled template/textchecker-element.esm.js instead of skypack
  - fix #78  
- Move template script to website-generator package
- Update Vite
- Use `message.range` for showing error
  - It allow to show more detail positions about that error
  - https://github.com/textlint/textlint/releases/tag/v12.2.0
- Update website design

image

### CODE REVIEW

File: packages/textchecker-element/src/util/logger.ts [hunk 1]
```diff
@@ -1,6 +1,5 @@
-const debugStorageValue = localStorage.DEBUG || "";
-const DEBUG =
-    debugStorageValue === "*" || debugStorageValue.startsWith("@textlint") || process.env.NODE_ENV === "development";
```
Comment (azu) [inline packages/textchecker-element/src/util/logger.ts:3]: process.env still exists in build

File: packages/@textlint/website-generator/tools/website-generator.mjs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+        );
+};
+try {
+    // Write index.html
+    fs.writeFileSync(path.join(outputDir, "index.html"), createHTMLTemplate(), "utf-8");
+    // Copy public-dist/textchecker-element.esm.js to template/
+    fs.copyFileSync(
+        path.join(textcheckerElementDir, "./public-dist/textchecker-element.esm.js"),
+        path.join(outputDir, "textchecker-element.esm.js")
+    );
```
Comment (azu) [inline packages/@textlint/website-generator/tools/website-generator.mjs:26]: Copy html and dist scripts.

File: packages/textchecker-element/package.json [hunk 3]
```diff
@@ -39,8 +39,8 @@
         "dev": "vite",
         "website": "npm run compile:textlint && vite build",
         "build": "tsc -p . && tsc --project ./tsconfig.module.json",
-        "build:public-lib": "vite build --config vite.lib.config.js",
-        "website-generator": "ts-node tools/website-generator.ts",
+        "build:public-lib": "vite build --mode production --config vite.lib.config.js && npm run build:public-lib-backward-compat",
+        "build:public-lib-backward-compat": "cp public-dist/textchecker-element.esm.js public-dist/textchecker-element.es.js",
```
Comment (azu) [inline packages/textchecker-element/package.json:43]: It is for backward compatible.

Previously, `public-dist/textchecker-element.es.js` is published.
