### PR TITLE
fix(script-compiler): support `node:` prefix 

### LINKED ISSUE #88: [script-compiler] compile error with textlint-rule-prh
Upon enabling the latest version of `textlint-rule-prh` https://github.com/textlint-rule/textlint-rule-prh and  executing `textlint-script-compiler`, I get an error related to module resolution.

```
[
  {
    moduleIdentifier: 'node:os',
    moduleName: 'node:os',
    message: 'Module build failed: UnhandledSchemeError: Reading from "node:os" is not handled by plugins (Unhandled scheme).\n' +
      'Webpack supports "data:" and "file:" URIs by default.\n' +
      'You may need an additional plugin to handle "node:" URIs.\n' +
      '    at /workspace/node_modules/webpack/lib/NormalModule.js:838:25\n' +
      '    at Hook.eval [as callAsync] (eval at create (/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Object.processResource (/workspace/node_modules/webpack/lib/NormalModule.js:835:8)\n' +
      '    at processResource (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:397:2)\n' +
      '    at NormalModule._doBuild (/workspace/node_modules/webpack/lib/NormalModule.js:825:3)\n' +
      '    at NormalModule.build (/workspace/node_modules/webpack/lib/NormalModule.js:969:15)\n' +
      '    at /workspace/node_modules/webpack/lib/Compilation.js:1377:12\n' +
      '    at NormalModule.needBuild (/workspace/node_modules/webpack/lib/NormalModule.js:1257:32)',
    moduleId: 2999,
    moduleTrace: [ [Object], [Object] ],
    details: undefined,
    stack: 'ModuleBuildError: Module build failed: UnhandledSchemeError: Reading from "node:os" is not handled by plugins (Unhandled scheme).\n' +
      'Webpack supports "data:" and "file:" URIs by default.\n' +
      'You may need an additional plugin to handle "node:" URIs.\n' +
      '    at /workspace/node_modules/webpack/lib/NormalModule.js:838:25\n' +
      '    at Hook.eval [as callAsync] (eval at create (/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Object.processResource (/workspace/node_modules/webpack/lib/NormalModule.js:835:8)\n' +
      '    at processResource (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:397:2)\n' +
      '    at NormalModule._doBuild (/workspace/node_modules/webpack/lib/NormalModule.js:825:3)\n' +
      '    at NormalModule.build (/workspace/node_modules/webpack/lib/NormalModule.js:969:15)\n' +
      '    at /workspace/node_modules/webpack/lib/Compilation.js:1377:12\n' +
      '    at NormalModule.needBuild (/workspace/node_modules/webpack/lib/NormalModule.js:1257:32)\n' +
      '    at processResult (/workspace/node_modules/webpack/lib/NormalModule.js:764:19)\n' +
      '    at /workspace/node_modules/webpack/lib/NormalModule.js:866:5\n' +
      '    at /workspace/node_modules/loader-runner/lib/LoaderRunner.js:399:11\n' +
      '    at /workspace/node_modules/loader-runner/lib/LoaderRunner.js:221:19\n' +
      '    at /workspace/node_modules/webpack/lib/NormalModule.js:838:16\n' +
      '    at Hook.eval [as callAsync] (eval at create (/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n' +
      '    at Object.processResource (/workspace/node_modules/webpack/lib/NormalModule.js:835:8)\n' +
      '    at processResource (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:220:11)\n' +
      '    at iteratePitchingLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:171:10)\n' +
      '    at runLoaders (/workspace/node_modules/loader-runner/lib/LoaderRunner.js:397:2)',
    compilerPath: undefined
  },
```

It seems that the direct cause of this issue is related to adding `node:path` and `node:os`.
https://github.com/textlint-rule/textlint-rule-prh/pull/104

Although script-compiler use `node-polyfill-webpack-plugin`, it has come to my attention that Webpack's resolve.fallback setting does not inherently support URIs with the `node:` prefix.
https://github.com/webpack/webpack/issues/14166

I’m not familiar with JavaScript and Node.js.
I wonder if there are any known solutions or workarounds to this issue.

### PR DESCRIPTION
**Pull request by azu**
- Update textlint v14
  - [Release v14.0.0 · textlint/textlint](https://github.com/textlint/textlint/releases/tag/v14.0.0)
  - Drop Node.js 16 support
- Fix #88 
  - It remove `node:` prefix before imporing.

### CODE REVIEW

File: packages/@textlint/script-compiler/src/compiler.ts [hunk 1]
```diff
@@ -91,6 +91,12 @@ export const createWebpackConfig = ({
             new webpack.BannerPlugin({
                 banner: `textlinteditor:@@@ ${JSON.stringify(metadata)} @@@`
             }),
+            // Remove the `node:` prefix
+            // see: https://github.com/webpack/webpack/issues/14166
+            // see: https://github.com/web-infra-dev/rsbuild/pull/1402
+            new webpack.NormalModuleReplacementPlugin(/^node:/, (resource) => {
+                resource.request = resource.request.replace(/^node:/, "");
+            }),
```
Comment (azu) [inline packages/@textlint/script-compiler/src/compiler.ts:99]: Fix #88

File: packages/@textlint/script-compiler/.textlintrc.json [hunk 2]
```diff
@@ -1,6 +1,11 @@
 {
   "rules": {
     "no-dropping-the-ra": true,
-    "preset-ja-technical-writing": true
+    "preset-ja-technical-writing": true,
+    "prh": {
+      "rulePaths": [
+        "./prh.yml"
+      ]
+    }
```
Comment (azu) [inline packages/@textlint/script-compiler/.textlintrc.json:9]: Add prh as test
