### PR TITLE
fix(script-compiler): use static `import` instead of `require` for template

### LINKED ISSUE #84: Any plans to support ESM on textlint-script-compiler?
As a background, I am currently trying to combine [monaco-editor](https://github.com/microsoft/monaco-editor) with textlint so that users can easily try textlint in their browsers. In the meantime, I am hoping to create something that works as an Chrome extension, as follows:

image

It seems that textlint's ESM support is gradually progressing these days. So, my current interest on textlint/editor is whether textlint-script-compiler has any plans to support a feature that would generate code that could be read from ESM. Currently, I think it outputs code that contains `require`, so it can't be used from ESM, right?

Most Chrome extensions these days seem to be generated by Vite, which by default tries to create ESM packages, so I am happy to have the compiled code available from ESM. Of course, it is still possible to use code compiled by textlinter-script-compiler by adding a workaround to switch the package from ESM to CJS for this issue.

---

P.S. I simply wanted to ask the question to determine how to structure my project at thiis time, while communicating that there is such a motivation about textlint-script-compiler. If you have no particular plans, feel free to say "No" and close this issue.

### PR DESCRIPTION
**Pull request by azu**
Current script-compiler template use `require`.
webpack allow to compile it and inlining the module.
But, If package.json has type=module, webpack does not transpile `require`. (I dont know the reason).
To use static `import` is a safer way.

Additionaly, this change will help us to support ESM-ed rules/plugins.

fix #84

### CODE REVIEW

File: packages/@textlint/script-compiler/src/CodeGenerator/worker-codegen.ts [hunk 1]
```diff
@@ -59,41 +64,69 @@ export const generateCode = async (config: TextlintConfigDescriptor) => {
...
+    };
+    const createPluginImportCode = (a: TextlintConfigPlugin, index: number) => {
+        return `import __plugin${index} from "${a.moduleName}";`;
+    };
     return `// Generated webworker code by textlint-script-compiler
 import { TextlintKernel } from "@textlint/kernel";
 import { moduleInterop } from "@textlint/module-interop";
 import { parseOptionsFromConfig } from "@textlint/config-partial-parser"
+// import rules
+${config.rules.map(createImportCode).join("\n")}
```
Comment (azu) [inline packages/@textlint/script-compiler/src/CodeGenerator/worker-codegen.ts:98]:
```js

// Generated webworker code by textlint-script-compiler
import { TextlintKernel } from "@textlint/kernel";
import { moduleInterop } from "@textlint/module-interop";
import { parseOptionsFromConfig } from "@textlint/config-partial-parser"
// import rules
import __rule0 from "textlint-rule-no-dropping-the-ra";
// import filterRules

// import plugins
import __plugin0 from "@textlint/textlint-plugin-text";
import __plugin1 from "@textlint/textlint-plugin-markdown";
// ====
const kernel = new TextlintKernel();
const rules = [
    {
        "ruleId": "no-dropping-the-ra",
        "rule": moduleInterop(__rule0),
        "options": true
    }
];
const filterRules = [];
    
const plugins = [
    {
        "pluginId": "@textlint/text",
        "plugin": moduleInterop(__plugin0),
        "options": true
    },
    {
        "pluginId": "@textlint/markdown",
        "plugin": moduleInterop(__plugin1),
        "options": true
    }
];
const config = {
    rules: rules,
    filterRules: filterRules,
    plugins: plugins
};
// merge config
const assignConfig = (textlintrc) => {
    const userDefinedConfig = parseOptionsFromConfig(textlintrc);
    if (userDefinedConfig.rules) {
        config.rules = config.rules.map(rule => {
            const override = userDefinedConfig.rules.find(o => o.ruleId === rule.ruleId);
            return { ...rule, ...override };
        });
    }
    if (userDefinedConfig.filterRules) {
        config.filterRules = config.filterRules.map(rule => {
            const override = userDefinedConfig.filterRules.find(o => o.ruleId === rule.ruleId);
            return { ...rule, ...override };
        });
    }
    if (userDefinedConfig.plugins) {
        config.plugins = config.plugins.map(rule => {
            const override = userDefinedConfig.plugins.find(o => o.pluginId === rule.pluginId);
            return { ...rule, ...override };
        });
    }
};
self.addEventListener('error', (event) => {
    self.postMessage({
        command: "error",
        // wrapping any type error with Error
        error: new Error("unexpected error", {
            cause: event.error
        })
    })
});
self.addEventListener('unhandledrejection', (event) => {
    self.postMessage({
        command: "error",
        // wrapping any type error with Error
        error: new Error("unexpected unhandled promise rejection", {
            cause: event.reason
        })
    })
});
self.addEventListener('message', (event) => {
    const data = event.data;
    const rules = data.ruleId === undefined
        ? config.rules
        : config.rules.filter(rule => rule.ruleId === data.ruleId);
    switch (data.command) {
        case "merge-config":
            return assignConfig(data.textlintrc);
        case "lint":
            return kernel.lintText(data.text, {
                rules: rules,
                filterRules: config.filterRules,
                plugins: config.plugins,
                filePath: "/path/to/README" + data.ext,
                ext: data.ext,
            }).then(result => {
                return self.postMessage({
                    id: data.id,
                    command: "lint:result",
                    result
                });
            }).catch(error => {
                return self.postMessage({
                    id: data.id,
                    command: "error",
                    // wrapping any type error with Error
                    error: new Error("failed to lint text", {
                        cause: error
                    })
                })
            });
        case "fix":
            return kernel.fixText(data.text, {
                rules: rules,
                filterRules: config.filterRules,
                plugins: config.plugins,
                filePath: "/path/to/README" + data.ext,
                ext: data.ext,
            }).then(result => {
                return self.postMessage({
                    id: data.id,
                    command: "fix:result",
                    result
                });
            }).catch(error => {
                return self.postMessage({
                    id: data.id,
                    command: "error",
                    error
                })
            });
        default:
            console.log("Unknown command: " + data.command);
    }
});
// ====
self.postMessage({
    command: "init",
    metadata: process.env.TEXTLINT_SCRIPT_METADATA
});
```

An example template result for script-compier.
